### ISSUE TITLE
serialVersionUID is not set on Modifiables

### ISSUE THREAD

**Issue by ugrave** [immutables/immutables#281] opened 2016-03-14 12:59 UTC
For generated modifiables the serialVersionUID is not set even if the source interface is marked with @Serial.Version. For the generated immutable it works. Also if the serialVersionUID is defined by an abstract class its not copied to the modifiable.

**Comment by elucash** [comment] 2016-03-14 19:41
This is mostly "by design", but we can fix if it will be useful

**Comment by elucash** [comment] 2016-04-01 07:12
Apparently, this was released in 2.1.15, so you might want to check if it works as expected. Thank you

**Comment by ugrave** [comment] 2016-04-01 07:18
Hi,

i have already updated to the new version and it works. Nice work.

**Closed** 2016-04-01 07:19 UTC
Labels: enhancement
