### ISSUE TITLE
AllowNulls and SkipNulls attribute level annotations for collections

### ISSUE THREAD

**Issue by NeilRickards** [immutables/immutables#452] opened 2016-09-30 12:21 UTC
The functionality added by @elucash for #349 does not appear to be working for me.

From head of master I run `cd value-fixture/src/org/immutables/fixture/nullable && javac -cp value-2.3.2.jar NullableElements.java NullableUse.java SkipNulls.java`

The generated code includes null checks.  For example
``` java
public final Builder putBl(String key, int value) {
  this.bl.put(
      Objects.requireNonNull(key, "bl key"),
      Objects.requireNonNull(value, "bl value"));
  return this;
}
```

By stepping through, I find that `$AnnotationMirrors.from` is returning an empty List for the type arguments.

I am using javac 1.8.0_102.  Any ideas?

**Comment by elucash** [comment] 2016-10-01 00:45
@NeilRickards Very interesting, thank you for reporting this! On one hand, it consistently compiles to

```java

    public final Builder putBl(String key, Integer value) {
      this.bl.put(key, value);
      return this;
    }
```

during testing.  But using your method I was able to reproduce 

```java
public final Builder putBl(String key, int value) {
  this.bl.put(
      Objects.requireNonNull(key, "bl key"),
      Objects.requireNonNull(value, "bl value"));
  return this;
}
```

Of course, we need to figure out what's happening, please, let us know if you will have any additional findings.

**Comment by NeilRickards** [comment] 2016-10-01 13:13
Interesting.  Could you describe how you're running the tests?

**Comment by elucash** [comment] 2016-10-01 23:30
@NeilRickards I dunno, as usual using maven, also Travis CI executes this test: https://github.com/immutables/immutables/blob/master/value-fixture/test/org/immutables/fixture/nullable/NullableAttributesTest.java#L155 which passes.
The odd thing is that I can no longer compile it on my machine, ImmutableNullableElements appears to be missing...

**Comment by elucash** [comment] 2016-10-02 21:01
I've tried to remember how those things should work: It turns out, if I remember correctly,  `TypeMirror.getAnnotationMirrors` (which is used behind `AnnotationMirrors.from`) will be always empty for the (nested) type arguments under Javac. Most likely, the explanation why it works in tests is the fact that our tests are using https://github.com/google/error-prone compiler, which supposedly should add additional checks, but not fix or mask javac bugs. When I switched back to vanilla javac in tests I actually got the compilation error for test and the cause was the exact difference in the generated code that we are talking about here.
The bug in javac is probably https://bugs.openjdk.java.net/browse/JDK-8046916 or related. For now, the workaround is to use error-prone compiler (don't know about ECJ at the moment).

Tried a hack to get annotations from the source code, but Javac (as opposed to ECJ) don't have source ranges available on the MethodSymbols, at least directly accessible, so it requires to fully parse source code (if available) and match all method definitions and types to corresponding annotation processing elements. For not this issue is without a solution, just a workaround available and it's not recommended to be used except for experimentation.

**Comment by NeilRickards** [comment] 2016-10-03 10:18
Good to have an explanation for the difference.  That openjdk bug doesn't sound quite right as we're seening no annotations, rather than too many, and I don't think the types with one attribute (`List`) were working either.
Agreed, parsing the source doesn't sound like the way to go.

**Comment by NeilRickards** [comment] 2016-10-05 19:10
I'm not sure Value Attributes and are really buying much here.  Would it work to do something like this?
``` Java
@Value.Immutable
public interface TestClass {
  @Value.NullableElements
  List<Void> al();

  @Value.NullableElements(skip = true)
  List<String> sk();

  @Value.NullableElements
  Map<String, Integer> bl();

  @Value.NullableElements(skip = true)
  Map<String, Integer> sm();

  Set<String> rg();
}
```
We could also defaulting to Jdk collections for these, regardless of Style

**Comment by elucash** [comment] 2016-10-05 21:32
Well, if it is about making it actually work, we probably should employ the same BYOA (Bring Your Own Annotation) approach, just allow it be placed on an attribute.
This could be done (wonder why it hasn't been done this way). Thank you for the reminder!

**Comment by NeilRickards** [comment] 2016-10-05 22:19
True that would be the more minimal change.  We need to be careful not to match on every `@Nullable` tag, which has quite a different meaning.

In general though I'm not too keen on the match-by-name approach: it doesn't seem consistent with how the rest of Immutables has been coded; it loses some type-safety; and I'd be happier using an attribute provided by Immutables than providing my own.

**Comment by elucash** [comment] 2016-10-05 22:28
I see. The initial idea was like we are strongly against people using this feature except for pathological cases of maintaining compatibility with something, and having such annotation API would actually suggest like: "go ahead, use it". Maybe I'm just exaggerating

**Comment by NeilRickards** [comment] 2016-10-06 12:57
I get the idealogical argument, though presumably it's the same as for nullable fields, and in this case `@Nullable` is supported.
My use-case is representing responses from Elasticsearch, which does permit null values.  If I use Immutables currently I risk blowing-up when deserializing from JSON.
Thanks for all the help on this!

**Comment by elucash** [comment] 2016-10-07 05:46
We support any annotation which matches `Nullable` by a simple name, so both `android.support.annotation.Nullable` and `javax.annotation.Nullable` will work without distinction. I guess we could publish sample annotation as a separate module for this (`SkipNulls, `NullableElements`). I hope I can get to this on the weekend, stay tuned!

**Comment by NeilRickards** [comment] 2016-10-08 19:59
That would be fantastic!
If that's how Nullables work then I withdraw my concern - I'm a big fan of consistency.

**Comment by elucash** [comment] 2016-10-10 05:31
Just released 2.3.4 (currently propagating to Maven Central). Attribute level annotations are matched by simple names `AllowNulls` and `SkipNulls`. It will work for JDK collection elements and map values, map keys are not affected and, in general, desire for nulls as keys is considered a degenerated case). Will not work for guava collections.

Instead of supplying sample annotations, I guess, specifically for this case, it would be better to just mention them in the documentation alongside nullable attributes. So leaving this open for now as reminder to document it.

**Comment by NeilRickards** [comment] 2016-10-12 11:08
Just to confirm I tried this yesterday and it's working well.  Thanks very much!

Some suggestions, which I will submit a PR for if I can:
* add tests to ensure you can't add nulls elements to the fields in `NullableAttributes`
* add tests to ensure you can't set the collections in `NullAnnElements` and `NullablyElements` to null
* remove the need for `@Value.Style(jdkOnly = true)` by automatically using JDK collections where needed

**Comment by elucash** [comment] 2016-10-12 23:19
The addition of tests would be welcome!
I tried to implement auto-switch `@Value.Style(jdkOnly = true)`, but as it also became apparent that jdkOnly mode incurs creation of utility collection methods generated per each top-level immutable implementation class. I do not wish this to be transparent or automatic, or additional scanning to be added to inference this. There's a warning issued when nullness annotations are used when `jdkOnly=false`, so should not be a problem in practice. To avoid repetition of style annotation you should annotate package or use it as meta-annotation.

**Comment by elucash** [comment] 2016-10-19 08:03
released in 2.3.7
Added documentation section http://immutables.github.io/immutable.html#nulls-in-collection
Thank you!

**Closed by elucash** 2016-10-19 08:03 UTC
Labels: bug, docbug, enhancement

**Comment by niltonvasques** [comment] 2018-06-29 06:31
Since `@Target(ElementType.TYPE_USE)` annotation is only supported on android > 26. What is the recommendation to use this feature for old SDKs?

**Comment by elucash** [comment] 2018-06-30 09:14
@niltonvasques you can create method-targeted annotations with `SkipNulls` or `AllowNulls` names and put them on accessor methods. Shown here http://immutables.github.io/immutable.html#nulls-in-collection
