### ISSUE TITLE
Invalid generated code using parameterized, not-yet-generated types in attributes

### ISSUE THREAD

**Issue by io7m** [immutables/immutables#725] opened 2017-11-25 18:26 UTC
Hello. I seem to have upset `2.6.0-alpha2`:

https://github.com/io7m/immutables-bug-20171125

It seems like it might be because I'm making references to types that will be generated by the end of the package, but haven't been generated yet. This has never mattered before, but it seems like it matters now.

**Comment by io7m** [comment] 2017-11-26 11:24
A temporary workaround is to refer to the abstract value types instead of the generated immutable types. In other words, `PUnitNameType<T>` instead of `PUnitName<T>`. This obviously changes the semantics slightly... `PUnitNameType<T>` isn't guaranteed to refer to an immutable type.

**Comment by elucash** [comment] 2017-12-31 22:50
I wanted to write how is this is an old known issue, and that in order to workaround the bug in Java we have to parse underlying Java source (if this is possible) and so on; but then I've figured it out I wrote very similar ad-hoc parser for Encodings module, and after 2 hours of troubleshooting I was able to nail it down, so I guess we will be good with 2.6

**Comment by elucash** [comment] 2018-05-19 07:46
this should be fixed now, closing as duplicate of #548 just to avoid double counting

**Closed by elucash** 2018-05-19 07:46 UTC
Labels: duplicate
