### ISSUE TITLE
encodings: unable to use Option-like encoding when disabling the builder

### ISSUE THREAD

**Issue by emmanueltouzery** [immutables/immutables#614] opened 2017-05-16 09:13 UTC
I tried to adapt the immutables-javaslang Option builder for vavr in our project and was baffled for quite some time why it didn't work.
There are two things that we use from the option-specific encoder:

1. ability to have setters which take `T` as well as `Option<T>` (nice to have)
2. for JSON deserialization, the default value if the client doesn't send an Option field must be Option.none(), not null (critical for us)

Now the reason why this wasn't working for us is because we disabled the immutables builder.
We have a style with `defaults = @Value.Immutable(builder = false)`.
Our issue with the builder is the type-unsafety (in case you add a new field). We're aware of the staged builder but it brings class bloating concerns.

Now immutables has some builtin javaslang support. And with that builtin support we get Option support also when the builder is disabled. However with encodings, we loose this support when disabling the builder. It would seem it doesn't have to be like that. To be honest, I'm not sure whether it's an immutables issue (not possible at all through encodings currently) or a immutables-javaslang issue (possible through encodings, but not implemented like that in immutables-javaslang). I think it's the first situation so I'm opening the bug against this repository.

**Comment by elucash** [comment] 2017-05-17 00:31
If you use Jackson, you may try using https://github.com/vavr-io/vavr-jackson module in the same way we need adapters for Jdk8 and Guava types. Let me know if this solves the problem or any specific fix we need to apply in Immutables

**Comment by emmanueltouzery** [comment] 2017-05-17 04:42
no no we use vavr-jackson already. our setup works great with immutables, javaslang and javaslang-jackson, because immutables has builtin javaslang support. But now javaslang renamed to vavr: to get immutables integration we must use [immutables-javaslang.](https://github.com/immutables/immutables-javaslang/) -- except we modified it to work on vavr, which is trivial. That integration is achieved through immutables 'encodings'.

my problem is either with the encodings support in immutables or with the implementation in immutables-javaslang/our modified immutables-vavr. It turns out it works very well, as long as you have the immutables builder enabled. Disable the immutables builder (`defaults = @Value.Immutable(builder = false)`) and you loose the encodings integration feature in the case of vavr.

I would like to be able to use the encodings integration feature even when the builder is disabled. As mentioned, current immutables has builtin integration for javaslang. That builtin integration does not stop working when you disable the builder.

[Here](https://github.com/immutables/immutables-javaslang/blob/0963f4d387d0f72ca15d2ca4b994f0912cd6e67c/javaslang-encodings/src/main/java/org/immutables/javaslang/encodings/JavaslangOptionEncoding.java#L33) we can see that most of the immutables-javaslang encodings code is under a builder section.

Now either immutables-javaslang is doing this integration through a builder section and it could be done another way... (what is particularly important for us is @Encoding.Init). Either it's the only encodings operation mode and the immutables encoding feature itself would maybe have to be expanded. I bet it's the second situation hence opened a bug here.

I probably should add @io7m in CC to this bug.

**Comment by elucash** [comment] 2017-05-17 04:54
I'm fairly aware of the difference between built-in integration I've added a way back and the encoding stuff we've introduced later. The problem is still not clear for me (I'm sorry but at the moment I don't have enough time to fully reproduce it myself). Here I can only rely on your help to figure out what the problem is. Let's say you've introduced a constructor parameter of the type `Option<T>`, then the deserialization module should supply `Option.none()` for `null` or absent attribute to construct the immutable object using the constructor. What piece of code (regular or generated code) prevents it from behaving that way? Once identified it would be more clear how we can fix it

**Comment by emmanueltouzery** [comment] 2017-05-17 05:04
I'll make a reproduction project. Would that help?

**Comment by emmanueltouzery** [comment] 2017-05-17 05:06
Will have to be two projects though one for encodings one for the use point. Will try to keep as small as possible.

**Comment by elucash** [comment] 2017-05-17 05:16
I've just added a "blind fix" which might solve the issue, but I haven't checked it (at all), just something that had occurred to me.
The idea is that for Jackson integration special `Json` object is generated. This object is used as an intermediate binding mechanism. If a certain property is not set it will use the default value. This will use `null` for a mutable field of a reference type. However, encoding should be able to define such default values by assigning an implementation field.

Can you please check Immutables' snapshots 1.5.1-SNAPSHOT from sonatype oss snapshots repo (or, alternatively, build from the latest source) along with making the following change to the encoding:

```java
@Encoding.Impl
private Option<T> field = Option.none();
                     // ^^^^^^^^^^^^^^^^
```

If this will not help, then repro project will definitely help

**Comment by emmanueltouzery** [comment] 2017-05-17 12:57
yes I confirm the fix works. The generated code has spurious carriage returns though:

```
    Option<Integer> fieldName = 
  Option.none()
  ;
```
another issue: it seems in a way it breaks compatiblity for the encoding API. If you previously didn't specify a default value (and presumably you wouldn't), now you'll get an error:

```
[ERROR] Could not generate constructor. Attribute 'name' does not have default value.
```

Adding the default value everything is fine.

And finally the biggest downside for me is that it fixes only one of the issues. It fixes the big one, definitely. The other limitation I can live with, it's just a shame: the other thing is the ability to have setters (with* functions) which take `T` as well as `Option<T>`. That is still lost with encodings when you disable the builder even with that improvement.

**Comment by emmanueltouzery** [comment] 2017-05-17 13:01
Also, maybe it's worth considering this for all possible encoding types, not only option-like. But I can't say much about that, as we use these integration features only for option-like types.

**Comment by elucash** [comment] 2017-05-18 05:34
Not all encoding need default value. Option or some collection can default to some "empty" value. Most of the normal types not only will actually require value to be set, but also do not possibly have sensible default value. The error you've listed is when default value need to be set in constructor but it's not defined for a type: i.e. when singleton is enabled or when attribute is left out of constructor (when there are other `Parameter` attributes, but not this one).
@emmanueltouzery please, elaborate cases which might have been broken with regard to the error you've mentioned.

The extra newlines to be fixed, stay tuned.

Encodings provides the way to "encode" `with*`  methods with custom signatures. It's not yet in the tutorial, but there's javadoc on `@Encoding.Copy` and error messages if misused.

```java
// we you specify one of the copy methods, the default one is not longer generated
// so you need to declare both alternative setters
@Encoding.Copy
public Option<T> with(Option<T> value) {
   return Objects.requireNonNull(value); // insert any checks necessary
}
@Encoding.Copy
public Option<T> with(T value) {
   return Option.some(value); // insert any checks necessary
}
```

Maybe this is something to request for the vavr encodings to implement: I.e. default values and wither methods where applicable.
/cc @io7m

**Comment by emmanueltouzery** [comment] 2017-05-18 07:00
thank you for the help!

that's it! I think now everything works perfectly for me. Here's my vavr option integration encoding:

```
@Encoding
class VavrOptionEncoding<T>
{
    @Encoding.Impl
    private Option<T> field = Option.none();

    @Encoding.Copy
    public Option<T> withOption(Option<T> value) {
        return Objects.requireNonNull(value);
    }

    @Encoding.Copy
    public Option<T> with(T value) {
        return Option.some(value);
    }
}
```

it is quite different from the one in immutables-javaslang, which puts everything in the builder tag. I guess now I just have to sit back and wait for the next immutables release, then we can migrate from javaslang to vavr, thanks a lot!

I'm keeping this bug open in case it's helpful for you (you mentioned the extra newlines), but feel free to close it anytime.

**Comment by io7m** [comment] 2017-07-02 11:05
@emmanueltouzery I've just pushed another `0.4.0-SNAPSHOT` of the `immutables-vavr` encodings to Sonatype's snapshot repository. It contains the adjustments you made to the `Option` encoding above. Any chance you could test your code against the snapshot? If it works, I'll push it as part of the `0.4.0` release.

**Comment by io7m** [comment] 2017-07-02 17:16
Going to close this now. It all seems to be resolved.

**Closed by io7m** 2017-07-02 17:16 UTC
