### ISSUE TITLE
Overriden methods should be generated with @Override

### ISSUE THREAD

**Issue by xenoterracide** [immutables/immutables#515] opened 2016-12-29 06:15 UTC
hmm... errorprone doesn't like this

```
[INFO] Compiling 13 source files to /pipeline/source/target/classes
/pipeline/source/target/generated-sources/annotations/com/xenoterracide/util/exception/TryPredicate.java:272: error: [MissingOverride] build implements method in Builder; expected @Override
    public TryPredicate<T> build() {
                           ^
    (see http://errorprone.info/bugpattern/MissingOverride)
  Did you mean '@Override public TryPredicate<T> build() {'?
1 error
```

my error prone config
```
    <errorprone.version>2.0.14</errorprone.version>
    <errorprone.plexuscompiler.version>2.8.1</errorprone.plexuscompiler.version>
```
```
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <configuration>
          <compilerId>javac-with-errorprone</compilerId>
          <forceJavacCompilerUse>true</forceJavacCompilerUse>
          <showDeprecation>true</showDeprecation>
          <showWarnings>true</showWarnings>
          <compilerArgs>
            <arg>-Xep:MissingOverride:ERROR</arg>
            <arg>-XepDisableWarningsInGeneratedCode</arg>
          </compilerArgs>
        </configuration>
        <dependencies>
          <dependency>
            <groupId>org.codehaus.plexus</groupId>
            <artifactId>plexus-compiler-javac-errorprone</artifactId>
            <version>${errorprone.plexuscompiler.version}</version>
          </dependency>
          <dependency>
            <groupId>com.google.errorprone</groupId>
            <artifactId>error_prone_core</artifactId>
            <version>${errorprone.version}</version>
          </dependency>
        </dependencies>
      </plugin>
```

getting this failure though on an immutables generated class.

source of generation
```
package com.xenoterracide.util.exception;


import java.util.function.Predicate;

import org.immutables.value.Value;

@Value.Immutable
@Value.Style(
    builderVisibility = Value.Style.BuilderVisibility.PUBLIC,
    visibility = Value.Style.ImplementationVisibility.PUBLIC,
    typeImmutable = "*",
    strictBuilder = true,
    typeAbstract = "*Def"
)
abstract class TryPredicateDef<T> implements TryDefinition<Boolean> {

    @org.immutables.builder.Builder.Parameter
    abstract PredicateThrower<T> successHandler();

    @FunctionalInterface
    public interface PredicateThrower<I> {
        boolean test( I input ) throws Throwable;
    }

    abstract static class Builder<T> implements Predicate<T> {
        @Override
        public boolean test( final T t ) {
            TryPredicate<T> impl = build();
            try {
                return impl.successHandler().test( t );
            }
            catch ( final Throwable e ) {
                impl.catchHandler().accept( e );
                return impl.defaultValue().orElse( false );
            }
        }

        abstract TryPredicate<T> build();
    }
}
```

probably related to this old upstream issue https://github.com/google/error-prone/issues/329

**Comment by elucash** [comment] 2016-12-29 07:43
yes, this is a known issue (see #202). I hope we can improve this, but this requires writing heavyweight analysis code which also will impact compilation/annotation-processing time. As of now it has pretty low priority. I know that you want extra rigorousness, but how about switch this check back into a warning?

**Comment by xenoterracide** [comment] 2016-12-29 08:47
if it's a warning, I'd never see it because the CI build won't fail, and as a warning I'd love to know where it's getting emitted in maven land...

```
/bin/bash
mvn is installed
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T16:41:47+00:00)
Maven home: /usr/share/maven
Java version: 1.8.0_111, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-openjdk-amd64/jre
Default locale: en, platform encoding: UTF-8
OS name: "linux", version: "4.8.4-coreos", arch: "amd64", family: "unix"
[INFO] Scanning for projects...
[INFO] Downloading: https://nexus.xenoterracide.com/content/repositories/snapshots/com/xenoterracide/platform/0.1.39-SNAPSHOT/maven-metadata.xml
[INFO] Downloaded: https://nexus.xenoterracide.com/content/repositories/snapshots/com/xenoterracide/platform/0.1.39-SNAPSHOT/maven-metadata.xml (606 B at 2.7 KB/sec)
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building util 0.1.4-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] Downloading: https://nexus.xenoterracide.com/content/repositories/snapshots/com/xenoterracide/logging/0.1.0-SNAPSHOT/maven-metadata.xml
[INFO] Downloaded: https://nexus.xenoterracide.com/content/repositories/snapshots/com/xenoterracide/logging/0.1.0-SNAPSHOT/maven-metadata.xml (2 KB at 51.2 KB/sec)
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ util ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /pipeline/source/src/main/resources
[INFO] skip non existing resourceDirectory /pipeline/source/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ util ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 13 source files to /pipeline/source/target/classes
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.218 s
[INFO] Finished at: 2016-12-29T06:42:24+00:00
[INFO] Final Memory: 33M/1226M```

**Comment by elucash** [comment] 2017-01-08 23:39
Would you mind if I close this as a duplicate of #202

**Comment by xenoterracide** [comment] 2017-01-09 01:21
guess not.

**Closed** 2017-01-09 01:21 UTC
Labels: duplicate
