### ISSUE TITLE
Depluralization should NOT affect addXYZ(ABC... elements)

### ISSUE THREAD

**Issue by vorburger** [immutables/immutables#753] opened 2018-02-19 15:46 UTC
Given something like this:

```java
@Value.Immutable
@Value.Style(visibility = Value.Style.ImplementationVisibility.PRIVATE, depluralize = true)
public abstract class WebContext {
    public abstract List<ServletRegistration> servlets();
}
```

generates (among other things) e.g. 

    WebContextBuilder addServlet(ServletRegistration element)

    WebContextBuilder addAllServlets(Iterable<? extends ServletRegistration> elements)

which are great, but also:

    WebContextBuilder addServlet(ServletRegistration... elements)

which IMHO should be named addServlet**s**, not addServlet?

**Comment by elucash** [comment] 2018-02-21 20:21
Hi Michael, this is not about de-pluralization specifically, but more about how these were designed initially, i.e. vararg variant was designed as an overload of `addElement` rather than `addAllElements` (or separate `addElements`). IIRC the was some intentions on my part to revise this, please see #692

**Comment by elucash** [comment] 2018-05-17 20:17
closing as duplicate of completed #692

**Closed by elucash** 2018-05-17 20:17 UTC
Labels: duplicate
