### ISSUE TITLE
2.1.16 includes @Derived attributes in the generated constructors

### ISSUE THREAD

**Issue by gowong** [immutables/immutables#306] opened 2016-04-21 04:08 UTC
Derived attributes cannot be manually set so they should not be listed as a parameter in the constructor.
2.1.15 has the correct behavior.

**Comment by elucash** [comment] 2016-04-21 05:27
Thank you for the issue report! I'm kinda getting what the issue is, but can you please elaborate a bit in terms of expected/actual behavior.

**Comment by gowong** [comment] 2016-04-21 06:00
Sure, so say we have a class:
```java
@Value.Immutable
public abstract class Order {

  public abstract List<Item> items();

  @Value.Derived
  public int totalCount() {
    int count = 0;

    for (Item i : items())
      count += i.count();

    return count;
  }
}
```

The generated constructor should be
```java
public Order(List<Item> items) { ... }
```
but instead it's actually
```java
public Order(List<Item> items, int totalCount) { ... }
```

It doesn't make sense for the constructor to expect a derived attribute to be passed in.

**Comment by elucash** [comment] 2016-04-21 06:23
It should involve `Style(allParameters)` defined somewhere, otherwise parameters should not be listed without `@Value.Parameter`. Anyway, as you mention, derived attributes should not propagate to a constructor arguments.

**Comment by gowong** [comment] 2016-04-21 07:01
Right, I didn't include it in the example but I am setting `allParameters = true` in my style

**Comment by elucash** [comment] 2016-04-27 05:01
released in v2.1.18, thank you!

**Closed by elucash** 2016-04-27 05:01 UTC
