### ISSUE TITLE
Issue with Builder#from() for super class

### ISSUE THREAD

**Issue by almozavr** [immutables/immutables#395] opened 2016-07-12 12:33 UTC
## Scope
```java
class Identifiable<T> {
  T id();
}
class UniqueIdentifiable {
  String uid();
}
class Item implements Identifiable<Integer>, UniqueIdentifiable {
  ...
}
@Value.Immutable
class ItemSimple extends Item{...}
@Value.Immutable
class ItemExtended extends Item{...}
```
## Problem
`ImmutableItemSimple#from()` and `ImmutableItemExtended#from()` are generated with errors:
```java
private void from(Object object) {
      if (object instanceof UniqueIdentifiable) {
        UniqueIdentifiable instance = (UniqueIdentifiable) object;
        uid(instance.uid());
      }
      if (object instanceof ItemSimple) { // should be instance of Identifiable
        BucketItemSimple instance = (BucketItemSimple) object; // should be Identifiable
        id(instance.id());
      }
}
```
Seems like problem is in `<T>` typed base interface.

**Comment by elucash** [comment] 2016-07-12 21:10
I've just faced similar problem with covariant override of return type. Currently have no idea how to resolve it. Should we just skip the attribute in this case? Only assign such attributes from a supertype if statically known to be exactly of the same type? (thinking aloud)

**Comment by elucash** [comment] 2016-08-16 03:36
I've made a refinement to disallow any attribute assignment from supertype if supertype has not the same return type (as if supertype id return `Object id()` and subtype overrides with `String id()` and build from cannot get Object from supertype and assign it to String of a subtype (there's no intention to introduce runtime instanceof checks for this)). As it turned out, there is also restriction to not build from supertype if supertype have generic parameters, so reported behavior is, probably, by design. Overall I'm very reluctant to make this inheritance-related stuff perfect because there just no "correct" solution to this, overall, any non-trivial combination of parametric polymorphism and subtyping with covariant overrides is an unsound one.

**Closed** 2016-08-16 03:36 UTC
Labels: bug
