### ISSUE TITLE
2.1.16 generating code that uses Java 7 java.util.Objects

### ISSUE THREAD

**Issue by trask** [immutables/immutables#305] opened 2016-04-17 08:33 UTC
I wonder if it's not seeing that I have Guava on my classpath?  2.0.15 works fine for me.

**Comment by elucash** [comment] 2016-04-18 04:00
The problem is that I switched to 'java.util.Objects' detection before checking for guava. And if compiled under jdk7 for java 6 target this will give the non-desired result. Probably, we have to switch back to the old way of detection. sorry for inconvenience, will be fixed.

**Comment by trask** [comment] 2016-04-18 04:35
No problem.  It's ok for me if you want to drop Java 6 runtime support in 2.2 or whenever.  I don't mind being stuck on 2.1, it has had everything I need for some time now.  Thanks.

**Comment by elucash** [comment] 2016-04-27 04:38
Released in 2.1.18. Please let me know if it does not handle the issue. Thank you!

**Closed** 2016-04-27 05:01 UTC
Labels: bug

**Comment by Konsumierer** [comment] 2017-12-12 14:48
@elucash I am using Immutables v2.5.5, but my generated classes still use `Objects#requireNonNull` instead of the Guava equivalent, while `Sets` are correctly generated as Guava's `ImmutableSet`. The source targets Java 1.7 and is used in an Android app. As far as I understood, Guava should be detected on the classpath and then automatically be used instead of JDK 7 features?
Thanks.
