### ISSUE TITLE
Mongo Java Driver v3 support

### ISSUE THREAD

**Issue by zlangbert** [immutables/immutables#510] opened 2016-12-21 18:49 UTC
Hi, I was wondering what the status was of supporting more recent versions (3+) of the mongo java driver. Version 2 of the driver [does not support](https://docs.mongodb.com/ecosystem/drivers/java/#mongodb-compatibility) mongo 3.4. Is this something that is planned for the future?

Thanks!

**Comment by elucash** [comment] 2016-12-21 19:18
Hi, there's ticket for that #257 marked as "help needed". It's not over complex, but need some efforts to dig into the structure of the driver to perform the upgrade. Hope to get to it someday, but for now, I'm overloaded with other activities.

**Comment by elucash** [comment] 2017-02-04 07:31
Duplicate of #257, Help wanted. Closing this ticket

**Closed by elucash** 2017-02-04 07:31 UTC
Labels: duplicate
